* enc/make_encmake.rb: the list of encoding extension libraries must   not include encinit.c itself.  It caused "undefined reference to   Init_encinit".
git-svn-id: svn+ssh://ci.ruby-lang.org/ruby/trunk@50978 b2dd03c8-39d4-4d8f-98ff-823fe69b080e